name: echo
on:
  push:
    branches:
      - main
jobs:
  echo-task:
    name: echo a string
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Hello!"
  echo-something-else:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Hello again!"
