name: echo
on:
  push:
    branches:
      - main
jobs:
  echo-task:
    name: echo a string
    runs-on: ubuntu-latest
    steps:
      - name: Create script then run it
        run: echo "print('hello')" > main.py || python3 main.py
  echo-something-else:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Hello again!"
